MLX_DATA_LIB	= libmlx_data.a
MLX_DATA_SRCS	= libmlx_data.c libmlx_img.c
MLX_DATA_OBJS	= libmlx_data.o libmlx_img.o

COLORS_LIB		= libcolors.a
COLORS_SRCS		= colors.c
COLORS_OBJS		= $(COLORS_SRCS:%.c=%.o)
