MLX_DATA_LIB	= libmlx_data.a
MLX_DATA_SRCS	= libmlx_data.c img_4_byte.c
MLX_DATA_OBJS	= libmlx_data.o img_4_byte.o

COLORS_LIB		= libcolors.a
COLORS_SRCS		= colors.c
COLORS_OBJS		= $(COLORS_SRCS:%.c=%.o)
